/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "http://123.60.218.218:1236/oss/chx-test/d11ee601c7e25f077d2c9359996bbdd9"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "个人博客,技术文档,学习,面试,markdown"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#11a8cd"
      }
    ]
  ],
  "pages": [
    {
      "title": "VuePress安装",
      "frontmatter": {
        "title": "VuePress安装",
        "date": "2024-03-05T10:24:13.000Z",
        "permalink": "/pages/d62d1f/",
        "categories": [
          "开始",
          "博客搭建"
        ],
        "tags": [
          null
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/01.%E5%BC%80%E5%A7%8B/01.%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA/02.VuePress%E5%AE%89%E8%A3%85.html",
      "relativePath": "01.开始/01.博客搭建/02.VuePress安装.md",
      "key": "v-1cf8868e",
      "path": "/pages/d62d1f/",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "安装VuePress",
          "slug": "安装vuepress"
        }
      ],
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "技术选型",
      "frontmatter": {
        "title": "技术选型",
        "date": "2024-03-04T13:04:24.000Z",
        "permalink": "/pages/ba1743/",
        "categories": [
          "开始",
          "博客搭建"
        ],
        "tags": [
          "博客"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/01.%E5%BC%80%E5%A7%8B/01.%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA/01.%E6%8A%80%E6%9C%AF%E9%80%89%E5%9E%8B.html",
      "relativePath": "01.开始/01.博客搭建/01.技术选型.md",
      "key": "v-a9fe1212",
      "path": "/pages/ba1743/",
      "headers": [
        {
          "level": 3,
          "title": "静态网页和动态网页（来自GPT的解释^^）",
          "slug": "静态网页和动态网页-来自gpt的解释"
        },
        {
          "level": 4,
          "title": "动态和静态的优势劣势（摘抄）",
          "slug": "动态和静态的优势劣势-摘抄"
        },
        {
          "level": 4,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "技术选型",
          "slug": "技术选型"
        },
        {
          "level": 3,
          "title": "VuePress",
          "slug": "vuepress"
        }
      ],
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "Docker容器技术（摘抄）",
      "frontmatter": {
        "title": "Docker容器技术（摘抄）",
        "date": "2024-03-04T22:08:52.000Z",
        "permalink": "/pages/45d0d1/",
        "categories": [
          "博客",
          "Docker"
        ],
        "tags": [
          "Docker"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/03.%E5%8D%9A%E5%AE%A2/02.Docker/01.Docker%E5%AE%B9%E5%99%A8%E6%8A%80%E6%9C%AF.html",
      "relativePath": "03.博客/02.Docker/01.Docker容器技术.md",
      "key": "v-06401ab0",
      "path": "/pages/45d0d1/",
      "headers": [
        {
          "level": 2,
          "title": "容器技术入门",
          "slug": "容器技术入门"
        },
        {
          "level": 3,
          "title": "环境安装和部署",
          "slug": "环境安装和部署"
        },
        {
          "level": 3,
          "title": "从虚拟机到容器",
          "slug": "从虚拟机到容器"
        },
        {
          "level": 3,
          "title": "容器工作机制简述",
          "slug": "容器工作机制简述"
        },
        {
          "level": 2,
          "title": "容器与镜像",
          "slug": "容器与镜像"
        },
        {
          "level": 3,
          "title": "初识容器镜像",
          "slug": "初识容器镜像"
        },
        {
          "level": 3,
          "title": "镜像结构介绍",
          "slug": "镜像结构介绍"
        },
        {
          "level": 3,
          "title": "构建镜像",
          "slug": "构建镜像"
        },
        {
          "level": 3,
          "title": "发布镜像到远程仓库",
          "slug": "发布镜像到远程仓库"
        },
        {
          "level": 3,
          "title": "实战：使用IDEA构建SpringBoot程序镜像",
          "slug": "实战-使用idea构建springboot程序镜像"
        },
        {
          "level": 2,
          "title": "容器网络管理",
          "slug": "容器网络管理"
        },
        {
          "level": 3,
          "title": "容器网络类型",
          "slug": "容器网络类型"
        },
        {
          "level": 3,
          "title": "用户自定义网络",
          "slug": "用户自定义网络"
        },
        {
          "level": 3,
          "title": "容器间网络",
          "slug": "容器间网络"
        },
        {
          "level": 3,
          "title": "容器外部网络",
          "slug": "容器外部网络"
        },
        {
          "level": 2,
          "title": "容器存储管理",
          "slug": "容器存储管理"
        },
        {
          "level": 3,
          "title": "容器持久化存储",
          "slug": "容器持久化存储"
        },
        {
          "level": 3,
          "title": "容器数据共享",
          "slug": "容器数据共享"
        },
        {
          "level": 2,
          "title": "容器资源管理",
          "slug": "容器资源管理"
        },
        {
          "level": 3,
          "title": "容器控制操作",
          "slug": "容器控制操作"
        },
        {
          "level": 3,
          "title": "物理资源管理",
          "slug": "物理资源管理"
        },
        {
          "level": 3,
          "title": "容器监控",
          "slug": "容器监控"
        },
        {
          "level": 2,
          "title": "单机容器编排",
          "slug": "单机容器编排"
        },
        {
          "level": 3,
          "title": "快速开始",
          "slug": "快速开始"
        },
        {
          "level": 3,
          "title": "部署完整项目",
          "slug": "部署完整项目"
        }
      ],
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "Docker部署Artalk",
      "frontmatter": {
        "title": "Docker部署Artalk",
        "date": "2024-03-05T01:43:41.000Z",
        "permalink": "/pages/1be984/",
        "categories": [
          "开始",
          "博客搭建"
        ],
        "tags": [
          "Docker",
          "博客",
          "Artalk"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/01.%E5%BC%80%E5%A7%8B/01.%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA/03.Docker%E9%83%A8%E7%BD%B2Artalk.html",
      "relativePath": "01.开始/01.博客搭建/03.Docker部署Artalk.md",
      "key": "v-492be53d",
      "path": "/pages/1be984/",
      "headers": [
        {
          "level": 2,
          "title": "Artalk",
          "slug": "artalk"
        },
        {
          "level": 2,
          "title": "部署",
          "slug": "部署"
        },
        {
          "level": 5,
          "title": "1. Docker创建对应容器",
          "slug": "_1-docker创建对应容器"
        },
        {
          "level": 5,
          "title": "2. 安全组设置",
          "slug": "_2-安全组设置"
        },
        {
          "level": 5,
          "title": "3.  创建管理员账户",
          "slug": "_3-创建管理员账户"
        },
        {
          "level": 5,
          "title": "4. 访问服务",
          "slug": "_4-访问服务"
        },
        {
          "level": 5,
          "title": "5.修改Arttalk配置",
          "slug": "_5-修改arttalk配置"
        },
        {
          "level": 5,
          "title": "6. 博客中引用Artalk",
          "slug": "_6-博客中引用artalk"
        }
      ],
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "Docker安装redis",
      "frontmatter": {
        "title": "Docker安装redis",
        "date": "2024-03-04T22:08:52.000Z",
        "permalink": "/pages/1f1321/",
        "categories": [
          "博客",
          "Docker"
        ],
        "tags": [
          "Docker"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/03.%E5%8D%9A%E5%AE%A2/02.Docker/02.Docker%E5%AE%89%E8%A3%85redis.html",
      "relativePath": "03.博客/02.Docker/02.Docker安装redis.md",
      "key": "v-b409a96e",
      "path": "/pages/1f1321/",
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "友链",
      "frontmatter": {
        "title": "友链",
        "date": "2024-03-04T16:30:53.000Z",
        "permalink": "/friends/",
        "categories": [
          "友链"
        ],
        "tags": [
          null
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/02.%E5%8F%8B%E9%93%BE/01.%E5%8F%8B%E9%93%BE.html",
      "relativePath": "02.友链/01.友链.md",
      "key": "v-144bab98",
      "path": "/friends/",
      "headers": [
        {
          "level": 2,
          "title": "我的友链",
          "slug": "我的友链"
        },
        {
          "level": 2,
          "title": "友链申请",
          "slug": "友链申请"
        }
      ],
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "README",
      "frontmatter": {
        "title": "README",
        "date": "2024-03-04T15:25:50.000Z",
        "permalink": "/pages/e01108/",
        "categories": [
          "开始"
        ],
        "tags": [
          "link"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/01.%E5%BC%80%E5%A7%8B/",
      "relativePath": "01.开始/README.md",
      "key": "v-7c921567",
      "path": "/pages/e01108/",
      "headers": [
        {
          "level": 2,
          "title": "记录博客的开始，包括以后的博客相关日常",
          "slug": "记录博客的开始-包括以后的博客相关日常"
        },
        {
          "level": 3,
          "title": "博客搭建",
          "slug": "博客搭建"
        }
      ],
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "使用Docker安装Hadoop，遇到的问题",
      "frontmatter": {
        "title": "使用Docker安装Hadoop，遇到的问题",
        "date": "2024-03-04T22:09:09.000Z",
        "permalink": "/pages/44d4dc/",
        "categories": [
          "博客",
          "Docker"
        ],
        "tags": [
          "Docker",
          "bug"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/03.%E5%8D%9A%E5%AE%A2/02.Docker/05.%E4%BD%BF%E7%94%A8Docker%E5%AE%89%E8%A3%85Hadoop%EF%BC%8C%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98.html",
      "relativePath": "03.博客/02.Docker/05.使用Docker安装Hadoop，遇到的问题.md",
      "key": "v-60b9ad8b",
      "path": "/pages/44d4dc/",
      "headers": [
        {
          "level": 2,
          "title": "File /** could only be replicated to 0 nodes instead of minReplication (=1).  There are 2 datanode(s) running and 2 node(s) are excluded in this operation.",
          "slug": "file-could-only-be-replicated-to-0-nodes-instead-of-minreplication-1-there-are-2-datanode-s-running-and-2-node-s-are-excluded-in-this-operation"
        },
        {
          "level": 3,
          "title": "1.问题描述",
          "slug": "_1-问题描述"
        },
        {
          "level": 3,
          "title": "2.排查错误",
          "slug": "_2-排查错误"
        },
        {
          "level": 6,
          "title": "1.查看datanode是否都启动成功",
          "slug": "_1-查看datanode是否都启动成功"
        },
        {
          "level": 6,
          "title": "2.查看web界面",
          "slug": "_2-查看web界面"
        },
        {
          "level": 6,
          "title": "4.通过shell命令测试上传和下载",
          "slug": "_4-通过shell命令测试上传和下载"
        },
        {
          "level": 6,
          "title": "5.Java使用的Hadoop jar包的问题",
          "slug": "_5-java使用的hadoop-jar包的问题"
        },
        {
          "level": 6,
          "title": "6.那为什么日志中说文件复制只能复制到0个节点呢？",
          "slug": "_6-那为什么日志中说文件复制只能复制到0个节点呢"
        },
        {
          "level": 6,
          "title": "7.通过shell上传和通过API进行上传有的区别",
          "slug": "_7-通过shell上传和通过api进行上传有的区别"
        },
        {
          "level": 6,
          "title": "8.现在可以确定是客户端与Docker容器之间的通信的问题了",
          "slug": "_8-现在可以确定是客户端与docker容器之间的通信的问题了"
        },
        {
          "level": 6,
          "title": "9.验证端口映射",
          "slug": "_9-验证端口映射"
        },
        {
          "level": 3,
          "title": "3.总结问题",
          "slug": "_3-总结问题"
        },
        {
          "level": 4,
          "title": "4.解决方案",
          "slug": "_4-解决方案"
        }
      ],
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "Docker中centos8安装mysql",
      "frontmatter": {
        "title": "Docker中centos8安装mysql",
        "date": "2024-03-04T22:08:52.000Z",
        "permalink": "/pages/40549b/",
        "categories": [
          "博客",
          "Docker"
        ],
        "tags": [
          "Docker"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/03.%E5%8D%9A%E5%AE%A2/02.Docker/04.Docker%E4%B8%ADcentos8%E5%AE%89%E8%A3%85mysql.html",
      "relativePath": "03.博客/02.Docker/04.Docker中centos8安装mysql.md",
      "key": "v-4bd71421",
      "path": "/pages/40549b/",
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "Redis学习",
      "frontmatter": {
        "title": "Redis学习",
        "date": "2024-03-04T22:11:24.000Z",
        "permalink": "/pages/a39425/",
        "categories": [
          "博客",
          "Redis"
        ],
        "tags": [
          "Redis"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/03.%E5%8D%9A%E5%AE%A2/01.Redis/01.Redis%E5%AD%A6%E4%B9%A0.html",
      "relativePath": "03.博客/01.Redis/01.Redis学习.md",
      "key": "v-fb5890ee",
      "path": "/pages/a39425/",
      "headers": [
        {
          "level": 2,
          "title": "概要",
          "slug": "概要"
        },
        {
          "level": 2,
          "title": "基本数据类型",
          "slug": "基本数据类型"
        },
        {
          "level": 3,
          "title": "1.Strings字符串",
          "slug": "_1-strings字符串"
        },
        {
          "level": 4,
          "title": "基本命令：key-value",
          "slug": "基本命令-key-value"
        },
        {
          "level": 4,
          "title": "过期时间命令：SET key value [EX seconds] [PX milliseconds]",
          "slug": "过期时间命令-set-key-value-ex-seconds-px-milliseconds"
        },
        {
          "level": 4,
          "title": "锁命令：key-value [nx|xx]",
          "slug": "锁命令-key-value-nx-xx"
        },
        {
          "level": 4,
          "title": "计数器命令：key-value",
          "slug": "计数器命令-key-value"
        },
        {
          "level": 3,
          "title": "2.Lists列表",
          "slug": "_2-lists列表"
        },
        {
          "level": 4,
          "title": "基本命令",
          "slug": "基本命令"
        },
        {
          "level": 4,
          "title": "队列、堆栈操作",
          "slug": "队列、堆栈操作"
        },
        {
          "level": 4,
          "title": "阻塞列表操作",
          "slug": "阻塞列表操作"
        },
        {
          "level": 3,
          "title": "3.sets集合",
          "slug": "_3-sets集合"
        },
        {
          "level": 4,
          "title": "基本命令",
          "slug": "基本命令-2"
        },
        {
          "level": 3,
          "title": "4.hashes哈希表",
          "slug": "_4-hashes哈希表"
        },
        {
          "level": 4,
          "title": "基本命令",
          "slug": "基本命令-3"
        },
        {
          "level": 3,
          "title": "5.sorted sets排序集合",
          "slug": "_5-sorted-sets排序集合"
        },
        {
          "level": 4,
          "title": "基本命令",
          "slug": "基本命令-4"
        },
        {
          "level": 3,
          "title": "6.streams流",
          "slug": "_6-streams流"
        },
        {
          "level": 4,
          "title": "基本命令",
          "slug": "基本命令-5"
        },
        {
          "level": 4,
          "title": "使用 XREAD 监听新项目",
          "slug": "使用-xread-监听新项目"
        },
        {
          "level": 4,
          "title": "消费群体",
          "slug": "消费群体"
        },
        {
          "level": 4,
          "title": "创建消费者组",
          "slug": "创建消费者组"
        },
        {
          "level": 4,
          "title": "自动认领",
          "slug": "自动认领"
        }
      ],
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "OSS",
      "frontmatter": {
        "title": "OSS",
        "date": "2024-03-04T23:21:14.000Z",
        "permalink": "/pages/5572a6/",
        "categories": [
          "博主の秘密",
          "OSS对象存储"
        ],
        "tags": [
          "OSS"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/04.%E5%8D%9A%E4%B8%BB%E3%81%AE%E7%A7%98%E5%AF%86/02.OSS%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8/01.OSS.html",
      "relativePath": "04.博主の秘密/02.OSS对象存储/01.OSS.md",
      "key": "v-3c976750",
      "path": "/pages/5572a6/",
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "在SpringBoot中导入本地Maven Jar包",
      "frontmatter": {
        "title": "在SpringBoot中导入本地Maven Jar包",
        "date": "2024-03-04T22:53:43.000Z",
        "permalink": "/pages/cc6154/",
        "categories": [
          "博客",
          "小技巧"
        ],
        "tags": [
          "小技巧"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/03.%E5%8D%9A%E5%AE%A2/03.%E5%B0%8F%E6%8A%80%E5%B7%A7/01.%E5%9C%A8SpringBoot%E4%B8%AD%E5%AF%BC%E5%85%A5%E6%9C%AC%E5%9C%B0Maven%20Jar%E5%8C%85.html",
      "relativePath": "03.博客/03.小技巧/01.在SpringBoot中导入本地Maven Jar包.md",
      "key": "v-29d5499c",
      "path": "/pages/cc6154/",
      "headers": [
        {
          "level": 3,
          "title": "1.将本地程序打成jar包",
          "slug": "_1-将本地程序打成jar包"
        },
        {
          "level": 3,
          "title": "2.导入SpringBoot工程",
          "slug": "_2-导入springboot工程"
        }
      ],
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "Docker上安装Hadoop",
      "frontmatter": {
        "title": "Docker上安装Hadoop",
        "date": "2024-03-04T22:08:52.000Z",
        "permalink": "/pages/ee1167/",
        "categories": [
          "博客",
          "Docker"
        ],
        "tags": [
          "Docker"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/03.%E5%8D%9A%E5%AE%A2/02.Docker/03.Docker%E4%B8%8A%E5%AE%89%E8%A3%85Hadoop.html",
      "relativePath": "03.博客/02.Docker/03.Docker上安装Hadoop.md",
      "key": "v-f7999330",
      "path": "/pages/ee1167/",
      "headers": [
        {
          "level": 2,
          "title": "1.安装前准备",
          "slug": "_1-安装前准备"
        },
        {
          "level": 2,
          "title": "2.配置容器基本环境",
          "slug": "_2-配置容器基本环境"
        },
        {
          "level": 4,
          "title": "1.安装centos",
          "slug": "_1-安装centos"
        },
        {
          "level": 3,
          "title": "2.创建具有基本环境的centos镜像",
          "slug": "_2-创建具有基本环境的centos镜像"
        },
        {
          "level": 3,
          "title": "3.创建有hadoop和jdk环境的镜像",
          "slug": "_3-创建有hadoop和jdk环境的镜像"
        },
        {
          "level": 3,
          "title": "4.创建网络，并启动docker容器",
          "slug": "_4-创建网络-并启动docker容器"
        },
        {
          "level": 3,
          "title": "5.配置域名映射与ssh免密登陆",
          "slug": "_5-配置域名映射与ssh免密登陆"
        },
        {
          "level": 3,
          "title": "6.配置hadoop",
          "slug": "_6-配置hadoop"
        },
        {
          "level": 3,
          "title": "7.启动Hadoop",
          "slug": "_7-启动hadoop"
        },
        {
          "level": 2,
          "title": "3.遇到的问题",
          "slug": "_3-遇到的问题"
        }
      ],
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "基于Hadoop的数据共享云平台",
      "frontmatter": {
        "title": "基于Hadoop的数据共享云平台",
        "date": "2024-03-04T23:13:31.000Z",
        "permalink": "/pages/2efa15/",
        "categories": [
          "博主の秘密",
          "云盘"
        ],
        "tags": [
          "云盘",
          "Hadoop"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/04.%E5%8D%9A%E4%B8%BB%E3%81%AE%E7%A7%98%E5%AF%86/01.%E4%BA%91%E7%9B%98/01.%E5%9F%BA%E4%BA%8EHadoop%E7%9A%84%E6%95%B0%E6%8D%AE%E5%85%B1%E4%BA%AB%E4%BA%91%E5%B9%B3%E5%8F%B0.html",
      "relativePath": "04.博主の秘密/01.云盘/01.基于Hadoop的数据共享云平台.md",
      "key": "v-5bfcefa0",
      "path": "/pages/2efa15/",
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Atliyasi Blog ^^",
        "tagline": "一个普通的学生，业余开发者，喜欢折腾新事物",
        "bannerBg": "/img/bd.jpg"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-9435e294",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "关于",
          "slug": "关于"
        },
        {
          "level": 3,
          "title": "📚Blog",
          "slug": "📚blog"
        },
        {
          "level": 2,
          "title": "✉️ 联系",
          "slug": "联系"
        }
      ],
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "重装系统后恢复nvm的版本控制",
      "frontmatter": {
        "title": "重装系统后恢复nvm的版本控制",
        "date": "2024-03-04T22:55:01.000Z",
        "permalink": "/pages/b11af4/",
        "categories": [
          "博客",
          "重装系统恢复系列"
        ],
        "tags": [
          "nvm",
          "npm"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/03.%E5%8D%9A%E5%AE%A2/04.%E9%87%8D%E8%A3%85%E7%B3%BB%E7%BB%9F%E6%81%A2%E5%A4%8D%E7%B3%BB%E5%88%97/01.%E9%87%8D%E8%A3%85%E7%B3%BB%E7%BB%9F%E5%90%8E%E6%81%A2%E5%A4%8Dnvm%E7%9A%84%E7%89%88%E6%9C%AC%E6%8E%A7%E5%88%B6.html",
      "relativePath": "03.博客/04.重装系统恢复系列/01.重装系统后恢复nvm的版本控制.md",
      "key": "v-294729b4",
      "path": "/pages/b11af4/",
      "headers": [
        {
          "level": 2,
          "title": "解决方案：",
          "slug": "解决方案"
        },
        {
          "level": 4,
          "title": "第一步先恢复nvm的环境变量",
          "slug": "第一步先恢复nvm的环境变量"
        },
        {
          "level": 4,
          "title": "第二步创建symlink（可以理解为快捷方式）",
          "slug": "第二步创建symlink-可以理解为快捷方式"
        },
        {
          "level": 4,
          "title": "第三步创建NVM_SYMLINK用户环境变量",
          "slug": "第三步创建nvm-symlink用户环境变量"
        },
        {
          "level": 4,
          "title": "第四步使用nvm进行版本切换",
          "slug": "第四步使用nvm进行版本切换"
        },
        {
          "level": 4,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "归档",
      "frontmatter": {
        "archivesPage": true,
        "title": "归档",
        "permalink": "/archives/",
        "article": false
      },
      "regularPath": "/@pages/archivesPage.html",
      "relativePath": "@pages/archivesPage.md",
      "key": "v-21e595ca",
      "path": "/archives/",
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "标签",
      "frontmatter": {
        "tagsPage": true,
        "title": "标签",
        "permalink": "/tags/",
        "article": false
      },
      "regularPath": "/@pages/tagsPage.html",
      "relativePath": "@pages/tagsPage.md",
      "key": "v-6468104a",
      "path": "/tags/",
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "分类",
      "frontmatter": {
        "categoriesPage": true,
        "title": "分类",
        "permalink": "/categories/",
        "article": false
      },
      "regularPath": "/@pages/categoriesPage.html",
      "relativePath": "@pages/categoriesPage.md",
      "key": "v-52b0e6aa",
      "path": "/categories/",
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "README",
      "frontmatter": {
        "title": "README",
        "date": "2024-03-04T22:15:51.000Z",
        "permalink": "/pages/bd08a7/",
        "categories": [
          "博客"
        ],
        "tags": [
          "link"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/03.%E5%8D%9A%E5%AE%A2/",
      "relativePath": "03.博客/README.md",
      "key": "v-7cae6a7a",
      "path": "/pages/bd08a7/",
      "headers": [
        {
          "level": 2,
          "title": "概要",
          "slug": "概要"
        }
      ],
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    },
    {
      "title": "README",
      "frontmatter": {
        "title": "README",
        "date": "2024-03-04T23:07:27.000Z",
        "permalink": "/pages/1182f3/",
        "categories": [
          "博主の秘密"
        ],
        "tags": [
          "link"
        ],
        "author": {
          "name": "Atliyasi",
          "link": "https://github.com/Atliyasi"
        }
      },
      "regularPath": "/04.%E5%8D%9A%E4%B8%BB%E3%81%AE%E7%A7%98%E5%AF%86/",
      "relativePath": "04.博主の秘密/README.md",
      "key": "v-0dc88b5d",
      "path": "/pages/1182f3/",
      "headers": [
        {
          "level": 3,
          "title": "收录一些咱写的项目 😊",
          "slug": "收录一些咱写的项目"
        }
      ],
      "lastUpdated": "2024/03/05, 11:20:55",
      "lastUpdatedTimestamp": 1709608855000
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "开始",
        "link": "/pages/e01108/"
      },
      {
        "text": "博客",
        "link": "/pages/bd08a7/"
      },
      {
        "text": "博主の秘密",
        "link": "/pages/1182f3/",
        "items": [
          {
            "text": "云盘",
            "link": "/pages/2efa15/"
          },
          {
            "text": "OSS对象存储",
            "link": "/pages/5572a6/"
          }
        ]
      },
      {
        "text": "Tags",
        "link": "/tags/",
        "items": [
          {
            "text": "分类",
            "link": "/categories/"
          },
          {
            "text": "标签",
            "link": "/tags/"
          }
        ]
      },
      {
        "text": "归档",
        "link": "/archives/"
      },
      {
        "text": "友情链接",
        "link": "/friends/"
      }
    ],
    "sidebarDepth": 1,
    "logo": "http://123.60.218.218:1236/oss/chx-test/d11ee601c7e25f077d2c9359996bbdd9",
    "repo": "Atliyasi",
    "searchMaxSuggestions": 10,
    "lastUpdated": "上次更新",
    "docsDir": "docs",
    "editLinks": false,
    "editLinkText": "编辑",
    "categoryText": "随笔",
    "sidebar": {
      "/01.开始/": [
        {
          "title": "博客搭建",
          "collapsable": true,
          "children": [
            [
              "01.博客搭建/01.技术选型.md",
              "技术选型",
              "/pages/ba1743/"
            ],
            [
              "01.博客搭建/02.VuePress安装.md",
              "VuePress安装",
              "/pages/d62d1f/"
            ],
            [
              "01.博客搭建/03.Docker部署Artalk.md",
              "Docker部署Artalk",
              "/pages/1be984/"
            ]
          ]
        }
      ],
      "catalogue": {},
      "/02.友链/": [
        [
          "01.友链.md",
          "友链",
          "/friends/"
        ]
      ],
      "/03.博客/": [
        {
          "title": "Redis",
          "collapsable": true,
          "children": [
            [
              "01.Redis/01.Redis学习.md",
              "Redis学习",
              "/pages/a39425/"
            ]
          ]
        },
        {
          "title": "Docker",
          "collapsable": true,
          "children": [
            [
              "02.Docker/01.Docker容器技术.md",
              "Docker容器技术（摘抄）",
              "/pages/45d0d1/"
            ],
            [
              "02.Docker/02.Docker安装redis.md",
              "Docker安装redis",
              "/pages/1f1321/"
            ],
            [
              "02.Docker/03.Docker上安装Hadoop.md",
              "Docker上安装Hadoop",
              "/pages/ee1167/"
            ],
            [
              "02.Docker/04.Docker中centos8安装mysql.md",
              "Docker中centos8安装mysql",
              "/pages/40549b/"
            ],
            [
              "02.Docker/05.使用Docker安装Hadoop，遇到的问题.md",
              "使用Docker安装Hadoop，遇到的问题",
              "/pages/44d4dc/"
            ]
          ]
        },
        {
          "title": "小技巧",
          "collapsable": true,
          "children": [
            [
              "03.小技巧/01.在SpringBoot中导入本地Maven Jar包.md",
              "在SpringBoot中导入本地Maven Jar包",
              "/pages/cc6154/"
            ]
          ]
        },
        {
          "title": "重装系统恢复系列",
          "collapsable": true,
          "children": [
            [
              "04.重装系统恢复系列/01.重装系统后恢复nvm的版本控制.md",
              "重装系统后恢复nvm的版本控制",
              "/pages/b11af4/"
            ]
          ]
        }
      ],
      "/04.博主の秘密/": [
        {
          "title": "云盘",
          "collapsable": true,
          "children": [
            [
              "01.云盘/01.基于Hadoop的数据共享云平台.md",
              "基于Hadoop的数据共享云平台",
              "/pages/2efa15/"
            ]
          ]
        },
        {
          "title": "OSS对象存储",
          "collapsable": true,
          "children": [
            [
              "02.OSS对象存储/01.OSS.md",
              "OSS",
              "/pages/5572a6/"
            ]
          ]
        }
      ]
    },
    "author": {
      "name": "Atliyasi",
      "link": "https://github.com/Atliyasi"
    },
    "blogger": {
      "avatar": "http://123.60.218.218:1236/oss/chx-test/8e2baa332e1455f2e60536dab95f3c55",
      "name": "Atliyasi",
      "slogan": "眼神清澈的大学生"
    },
    "social": {
      "icons": [
        {
          "iconClass": "icon-youjian",
          "title": "发邮件",
          "link": "mailto:1067037658@qq.com"
        },
        {
          "iconClass": "icon-github",
          "title": "GitHub",
          "link": "https://github.com/Atliyasi"
        },
        {
          "iconClass": "icon-erji",
          "title": "听音乐",
          "link": "https://music.163.com/playlist?id=2122598939&userid=1386351401"
        }
      ]
    },
    "footer": {
      "createYear": 2024,
      "copyrightInfo": "Atliyasi | <a href=\"https://github.com/Atliyasi\" target=\"_blank\">GitHub</a>"
    },
    "extendFrontmatter": {
      "author": {
        "name": "Atliyasi",
        "link": "https://github.com/Atliyasi"
      }
    },
    "htmlModules": {}
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "Atliyasi",
      "description": "Atliyasi个人博客",
      "path": "/"
    }
  }
}